RGB_MATRIX_ENABLE = no
RGBLIGHT_ENABLE = no
OLED_ENABLE     = no
COMBO_ENABLE = yes
TAP_DANCE_ENABLE = yes  # enable tap dance features
EXTRAKEY_ENABLE = yes
GRAVE_ESC_ENABLE = no
SPACE_CADET_ENABLE = no
AVR_USE_MINIMAL_PRINTF = yes
OS_DETECTION_ENABLE = yes
#WPM_ENABLE = yes
#CAPS_WORD_ENABLE = yes # if you hold down both shifts, you get lshift enabled for 1 word, but only works with KC shift, not MOD shift :(
#AUTO_SHIFT_ENABLE = yes
#UNICODE_ENABLE = yes     # enable unicode
